### PR TITLE
Add latvian language file

### PR DESCRIPTION
**Pull request by indriks**

### CODE REVIEW

**Comment by kajmagnus** [comment]
(B.t.w. thanks for submitting the PR  :- ))

**Comment by indriks** [comment]
1. Changed t_en_EN to t_lv_LV. That's Latvian language.
2. Agreed to CLA

**Comment by kajmagnus** [comment]
Hi @indriks ,  thanks for the changes & CLA — actually I cannot find any new / rewritten commits anywhere?

Did you possibly forget to push to GitHub?

When you do, it'd be good if you could please squash the commits into one?

**Comment by kajmagnus** [comment]
@indriks  — I'm thinking I can add the Latvian language file to a repository `ty-cla`, which is a bit less strict about people signing the CLA in "the right way".  How does that sound?  Then I'll just copy the file and you won't need to do anything more here.  Can I then use the info from your GitHub page as author / contributor info? https://github.com/indriks

**Comment by indriks** [comment]
Sounds good.

*Ivars Indriks*
Phone: +371 22017377
Web: indriks.com

**Comment by kajmagnus** [comment]
Hi @indriks ,  ok thanks :- )  The translation is now included in the latest version, I didn't bump the self hosted version number yet though.  Here's the commit:

https://github.com/debiki/ty-cla/commit/0fb65e9355d2cec2da15ff694f3d9c82980d61dc

**Pull request closed without merging**
