### PR TITLE
Adding German translation

### PR DESCRIPTION
**Pull request by jacotec**
I've translated and added a German (informal) i18n language file.
Should be listed as "Deutsch (Du)" in the language selection list

### CODE REVIEW

**Comment by jacotec** [comment]
By the way (as I've found it in other commit discussions) and to avoid further questions from your side:

I, Marco Jakobs, herewith agree to the CLA available here: https://github.com/debiki/talkyard/blob/master/docs/CLA-v2.txt

**Comment by kajmagnus** [comment]
Hi Marco @jacotec , thanks for the PR. I'll include in the upcoming version, at the end of this week (or early next week).

Could you please reopen the PR against repository `ty-cla` instead?  That's where the translations are nowadays.  Sorry that I haven't updated the documentation about this. (I'll do now)

https://github.com/debiki/ty-cla  (will get renamed to ty-translations)

If you're short of time, then I can move the translation to that other repo myself — I'm just not sure if the GitHub commit history then will link the commit over at that other repo, `ty-cla`, to your GitHub username.

I had a quick look at the PR, it looks fine.

**Comment by jacotec** [comment]
@kajmagnus Thanks, end of this or next week sounds great to me.
I'll check to open a PR in the other repo. I think this will be not before tomorrow, I hope that's OK for the next release (for which I'm waiting for my implementation). If time hurries and I did not make it until then, feel free to move it over.

**Comment by kajmagnus** [comment]
@jacotec  I've merged the commit into `ty-cla` — it worked fine, GitHub links to your profile, see:

https://github.com/debiki/ty-cla/commit/5c5dbeb72df18c86790682d20f0a5985435d8b3c

Will be incl in the upcoming version, available within some days.

I copied your comment about the CLA above, into the commit message. (One is actually supposed to type that text in the commit message,  never mind I did that now :-)   )

Thanks for the translation.  (I had a closer look, and found just two spaces `' '` to add / remove, everything else seemed fine)

**Comment by jacotec** [comment]
Thank you @kajmagnus . Sorry that I did not copy it over by myself ... currently it's a bit of a high workload here ;-)

**Pull request closed without merging**
