### PR TITLE
initial Hebrew translation

### PR DESCRIPTION
**Pull request by shmuel-krakower**
Please note I wanted to push *something* rather than nothing so its partial for now.
I've used a female form as suggested, when referring the user or other users. I used the male form when referring to objects (assuming the object is a male) but it might be wrong. I.e. a Message is a female while a Button is a male.
There might be some mismatches or wrong translation. Only once someone look at the translated UI he can and figure out the context of the word. I guess it will be ongoing with others to continue and translate as they use it, not sure when and if I'll continue the work here...

### CODE REVIEW

**Comment by kajmagnus** [comment]
Hi Shmuel, thanks for the translation & contrib :- )

I'll review and try this out.  Actually, I'm going to move the translations to a separate repository, where it's not that important to precisely & exactly follow the contributor guidelines about how to sign a CLA.  I'll message you once I've created that other repository

Interesting how different languages use "he" and "she" for different things

**Comment by kajmagnus** [comment]
Hi again Shmuel, (sorry for the a bit late reply)

Could you please either 1) reopen this PR but against https://github.com/debiki/ty-cla ?
*(I'm going to rename that repo to `ty-translations` a bit later — all translations will be there)*

Or 2) add a comment here in this PR that you agree to the CLA:  https://github.com/debiki/talkyard/blob/master/docs/CLA-v2.txt?
*(then I could copy your contribution myself to that other repository, if you rather want me to do that.)*

**Comment by shmuel-krakower** [comment]
Sure will do. I forgot about the CLA last time.

**Comment by shmuel-krakower** [comment]
replaced by https://github.com/debiki/ty-cla/pull/1

**Pull request closed without merging**
